Found 5 items
-rw-r--r--   3 root supergroup 1073741824 2019-03-27 10:24 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-03-27 10:24 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-03-27 10:24 /myfile3
-rw-r--r--   3 root supergroup 1073741824 2019-03-27 10:24 /myfile4
-rw-r--r--   3 root supergroup 1073741824 2019-03-27 10:24 /myfile5
file 2 has been put into HDFS
file 2 has been read from HDFS for 1 time
diff succeed!
file 2 has been read from HDFS for 2 time
diff succeed!
file 2 has been read from HDFS for 3 time
diff succeed!
2019-03-27 10:25:50,089 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:88)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1952)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1423)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3085)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1154)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:966)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 889ms.
2019-03-27 10:25:50,986 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode034.clemson.cloudlab.us/130.127.133.43 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2697ms.
file 2 has been read from HDFS for 4 time
diff succeed!
file 2 has been read from HDFS for 5 time
diff succeed!
file 2 has been read from HDFS for 6 time
diff succeed!
file 2 has been read from HDFS for 7 time
diff succeed!
file 2 has been read from HDFS for 8 time
diff succeed!
file 2 has been read from HDFS for 9 time
diff succeed!
file 2 has been read from HDFS for 10 time
diff succeed!
Deleted /myfile2
file 2 has been removed from HDFS
Found 5 items
-rw-r--r--   3 root supergroup 1073741824 2019-03-27 10:26 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-03-27 10:26 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-03-27 10:26 /myfile3
-rw-r--r--   3 root supergroup 1073741824 2019-03-27 10:26 /myfile4
-rw-r--r--   3 root supergroup 1073741824 2019-03-27 10:26 /myfile5
file 2 has been put into HDFS
2019-03-27 10:27:02,835 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.io.EOFException: End of File Exception between local host is: "clnode034.clemson.cloudlab.us/130.127.133.43"; destination host is: "node-0-link-0":8020; : java.io.EOFException; For more details see:  http://wiki.apache.org/hadoop/EOFException, while invoking ClientNamenodeProtocolTranslatorPB.getBlockLocations over node-0-link-0/10.10.1.1:8020. Trying to failover immediately.
2019-03-27 10:27:02,876 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:88)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1952)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1423)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1921)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:738)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:426)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
, while invoking ClientNamenodeProtocolTranslatorPB.getBlockLocations over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1002ms.
2019-03-27 10:27:03,882 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode034.clemson.cloudlab.us/130.127.133.43 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getBlockLocations over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1017ms.
file 2 has been read from HDFS for 1 time
diff succeed!
file 2 has been read from HDFS for 2 time
diff succeed!
file 2 has been read from HDFS for 3 time
diff succeed!
file 2 has been read from HDFS for 4 time
diff succeed!
file 2 has been read from HDFS for 5 time
