put: Exceeded the configured number of objects 4 in the filesystem.
file 2 has been put into HDFS
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 1 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 2 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 3 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 4 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 5 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 6 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 7 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
2019-03-27 04:26:14,074 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.io.IOException: DestHost:destPort node-1-link-0:8020 , LocalHost:localPort clnode034.clemson.cloudlab.us/130.127.133.43:0. Failed on local exception: java.io.IOException: Connection reset by peer, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1428ms.
2019-03-27 04:26:15,511 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:88)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1952)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1423)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3085)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1154)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:966)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1862ms.
2019-03-27 04:26:17,375 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode034.clemson.cloudlab.us/130.127.133.43 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3601ms.
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 8 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 9 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 10 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
rm: `/myfile2': No such file or directory
file 2 has been removed from HDFS
2019-03-27 04:26:37,334 WARN  hdfs.DataStreamer DataStreamer.java:run:826 - DataStreamer Exception
org.apache.hadoop.ipc.RemoteException(java.io.IOException): Exceeded the configured number of objects 4 in the filesystem.
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkFsObjectLimit(FSNamesystem.java:4724)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.analyzeFileState(FSDirWriteFileOp.java:594)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.validateAddBlock(FSDirWriteFileOp.java:172)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2679)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:875)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:561)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)

	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1497)
	at org.apache.hadoop.ipc.Client.call(Client.java:1443)
	at org.apache.hadoop.ipc.Client.call(Client.java:1353)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
	at com.sun.proxy.$Proxy11.addBlock(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:510)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy12.addBlock(Unknown Source)
	at org.apache.hadoop.hdfs.DFSOutputStream.addBlock(DFSOutputStream.java:1078)
	at org.apache.hadoop.hdfs.DataStreamer.locateFollowingBlock(DataStreamer.java:1865)
	at org.apache.hadoop.hdfs.DataStreamer.nextBlockOutputStream(DataStreamer.java:1668)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:716)
put: Exceeded the configured number of objects 4 in the filesystem.
file 2 has been put into HDFS
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 1 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 2 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 3 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 4 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 5 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 6 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 7 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 8 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 9 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 10 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
rm: `/myfile2': No such file or directory
file 2 has been removed from HDFS
2019-03-27 04:27:22,526 WARN  hdfs.DataStreamer DataStreamer.java:run:826 - DataStreamer Exception
org.apache.hadoop.ipc.RemoteException(java.io.IOException): Exceeded the configured number of objects 4 in the filesystem.
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkFsObjectLimit(FSNamesystem.java:4724)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.analyzeFileState(FSDirWriteFileOp.java:594)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.validateAddBlock(FSDirWriteFileOp.java:172)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2679)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:875)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:561)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)

	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1497)
	at org.apache.hadoop.ipc.Client.call(Client.java:1443)
	at org.apache.hadoop.ipc.Client.call(Client.java:1353)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
	at com.sun.proxy.$Proxy11.addBlock(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:510)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy12.addBlock(Unknown Source)
	at org.apache.hadoop.hdfs.DFSOutputStream.addBlock(DFSOutputStream.java:1078)
	at org.apache.hadoop.hdfs.DataStreamer.locateFollowingBlock(DataStreamer.java:1865)
	at org.apache.hadoop.hdfs.DataStreamer.nextBlockOutputStream(DataStreamer.java:1668)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:716)
put: Exceeded the configured number of objects 4 in the filesystem.
Found 1 items
-rw-r--r--   3 root supergroup  134217728 2019-03-27 04:27 /myfile4._COPYING_
file 2 has been put into HDFS
2019-03-27 04:27:27,510 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode034.clemson.cloudlab.us/130.127.133.43 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 559ms.
2019-03-27 04:27:28,077 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:88)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1952)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1423)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3085)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1154)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:966)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1365ms.
2019-03-27 04:27:29,445 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode034.clemson.cloudlab.us/130.127.133.43 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2284ms.
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 1 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 2 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 3 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 4 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 5 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
2019-03-27 04:27:49,264 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:88)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1952)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1423)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3085)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1154)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:966)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1434ms.
2019-03-27 04:27:50,706 INFO  retry.RetryInvocationHandler RetryInvocationHandler.java:log:411 - java.net.ConnectException: Call From clnode034.clemson.cloudlab.us/130.127.133.43 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1482ms.
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 6 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 7 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 8 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 9 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 10 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
rm: `/myfile2': No such file or directory
file 2 has been removed from HDFS
2019-03-27 04:28:15,157 WARN  hdfs.DataStreamer DataStreamer.java:run:826 - DataStreamer Exception
org.apache.hadoop.ipc.RemoteException(java.io.IOException): Exceeded the configured number of objects 4 in the filesystem.
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkFsObjectLimit(FSNamesystem.java:4724)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.analyzeFileState(FSDirWriteFileOp.java:594)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.validateAddBlock(FSDirWriteFileOp.java:172)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2679)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:875)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:561)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)

	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1497)
	at org.apache.hadoop.ipc.Client.call(Client.java:1443)
	at org.apache.hadoop.ipc.Client.call(Client.java:1353)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
	at com.sun.proxy.$Proxy11.addBlock(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:510)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy12.addBlock(Unknown Source)
	at org.apache.hadoop.hdfs.DFSOutputStream.addBlock(DFSOutputStream.java:1078)
	at org.apache.hadoop.hdfs.DataStreamer.locateFollowingBlock(DataStreamer.java:1865)
	at org.apache.hadoop.hdfs.DataStreamer.nextBlockOutputStream(DataStreamer.java:1668)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:716)
put: Exceeded the configured number of objects 4 in the filesystem.
Found 1 items
-rw-r--r--   3 root supergroup          0 2019-03-27 04:28 /myfile5._COPYING_
file 2 has been put into HDFS
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 1 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 2 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 3 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
get: `/myfile2': No such file or directory
TEST_ERROR: get failed!
file 2 has been read from HDFS for 4 time
diff: /root/hdfs-root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/hdfs-root/my_large_file/tmp/myfile2': No such file or directory
